/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/75.glb --transform -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube193: THREE.Mesh
    Cube193_1: THREE.Mesh
    Cube193_2: THREE.Mesh
  }
  materials: {
    ['outliner 0.025']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/75-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.15, -2.29]}>
        <mesh geometry={nodes.Cube193.geometry} material={materials['outliner 0.025']} />
        <mesh geometry={nodes.Cube193_1.geometry} material={materials['outliner 0.025']} />
        <mesh geometry={nodes.Cube193_2.geometry} material={materials['outliner 0.025']} />
      </group>
    </group>
  )
}

useGLTF.preload('/75-transformed.glb')
