/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/portal.glb --transform -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    floor: THREE.Mesh
    floor001: THREE.Mesh
    fence001: THREE.Mesh
    fence007: THREE.Mesh
    fence002: THREE.Mesh
    fence003: THREE.Mesh
    fence004: THREE.Mesh
    fence005: THREE.Mesh
    fence006: THREE.Mesh
    stump: THREE.Mesh
    stump004: THREE.Mesh
    stump001: THREE.Mesh
    stump005: THREE.Mesh
    stump002: THREE.Mesh
    stump006: THREE.Mesh
    stump003: THREE.Mesh
    stump007: THREE.Mesh
    firewood: THREE.Mesh
    firewood004: THREE.Mesh
    firewood001: THREE.Mesh
    firewood005: THREE.Mesh
    firewood002: THREE.Mesh
    firewood006: THREE.Mesh
    firewood003: THREE.Mesh
    firewood007: THREE.Mesh
    axe_handle: THREE.Mesh
    axe_handle001: THREE.Mesh
    axe_head: THREE.Mesh
    axe_head001: THREE.Mesh
    pole001: THREE.Mesh
    pole002: THREE.Mesh
    housing001: THREE.Mesh
    housing002: THREE.Mesh
    mount001: THREE.Mesh
    mount002: THREE.Mesh
    pole: THREE.Mesh
    housing: THREE.Mesh
    mount: THREE.Mesh
    rock: THREE.Mesh
    rock023: THREE.Mesh
    rock011: THREE.Mesh
    rock024: THREE.Mesh
    rock001: THREE.Mesh
    rock025: THREE.Mesh
    rock020: THREE.Mesh
    rock026: THREE.Mesh
    rock002: THREE.Mesh
    rock027: THREE.Mesh
    rock012: THREE.Mesh
    rock028: THREE.Mesh
    rock003: THREE.Mesh
    rock029: THREE.Mesh
    rock019: THREE.Mesh
    rock030: THREE.Mesh
    rock004: THREE.Mesh
    rock031: THREE.Mesh
    rock013: THREE.Mesh
    rock032: THREE.Mesh
    rock005: THREE.Mesh
    rock033: THREE.Mesh
    rock018: THREE.Mesh
    rock034: THREE.Mesh
    rock006: THREE.Mesh
    rock035: THREE.Mesh
    rock007: THREE.Mesh
    rock036: THREE.Mesh
    rock017: THREE.Mesh
    rock037: THREE.Mesh
    rock008: THREE.Mesh
    rock038: THREE.Mesh
    rock014: THREE.Mesh
    rock039: THREE.Mesh
    rock015: THREE.Mesh
    rock040: THREE.Mesh
    rock009: THREE.Mesh
    rock041: THREE.Mesh
    rock016: THREE.Mesh
    rock010: THREE.Mesh
    rock021: THREE.Mesh
    rock022: THREE.Mesh
    rock045: THREE.Mesh
    portal: THREE.Mesh
    portal002: THREE.Mesh
    stairs001: THREE.Mesh
    stairs003: THREE.Mesh
    stairs: THREE.Mesh
    stairs004: THREE.Mesh
    stairs002: THREE.Mesh
    stairs005: THREE.Mesh
    lamp: THREE.Mesh
    lamp001: THREE.Mesh
    lamp002: THREE.Mesh
    lamp003: THREE.Mesh
    portal001: THREE.Mesh
    portal003: THREE.Mesh
    fence008: THREE.Mesh
    fence009: THREE.Mesh
    fence010: THREE.Mesh
    fence011: THREE.Mesh
    fence012: THREE.Mesh
    pole003: THREE.Mesh
    housing003: THREE.Mesh
    mount003: THREE.Mesh
    rock042: THREE.Mesh
    rock043: THREE.Mesh
    rock044: THREE.Mesh
  }
  materials: {
    grass: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    lampLight: THREE.MeshStandardMaterial
    portalLight: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/portal-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor.geometry} material={materials.grass} />
      <mesh geometry={nodes.floor001.geometry} material={materials.grass} />
      <mesh geometry={nodes.fence001.geometry} material={materials.grass} position={[0.71, 0.22, 1.49]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.fence007.geometry} material={materials.grass} position={[0.71, 0.22, 1.49]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.fence002.geometry} material={materials.grass} position={[0.73, 0.22, 0.49]} rotation={[Math.PI / 2, 0, -3.05]} />
      <mesh geometry={nodes.fence003.geometry} material={materials.grass} position={[0.78, 0.22, -0.51]} rotation={[Math.PI / 2, 0, 3.13]} />
      <mesh geometry={nodes.fence004.geometry} material={materials.grass} position={[-0.92, 0.22, 1.47]} rotation={[Math.PI / 2, 0, 0.09]} />
      <mesh geometry={nodes.fence005.geometry} material={materials.grass} position={[-0.83, 0.22, 0.49]} rotation={[Math.PI / 2, 0, 0.02]} />
      <mesh geometry={nodes.fence006.geometry} material={materials.grass} position={[-0.79, 0.22, -0.5]} rotation={[Math.PI / 2, 0, 0.15]} />
      <mesh geometry={nodes.stump.geometry} material={materials.grass} position={[1.12, 0.1, 1.65]} />
      <mesh geometry={nodes.stump004.geometry} material={materials.grass} position={[1.12, 0.1, 1.65]} />
      <mesh geometry={nodes.stump001.geometry} material={materials.grass} position={[1.63, 0.07, 0.45]} />
      <mesh geometry={nodes.stump005.geometry} material={materials.grass} position={[1.63, 0.07, 0.45]} />
      <mesh geometry={nodes.stump002.geometry} material={materials.grass} position={[1.16, 0.05, 0.83]} />
      <mesh geometry={nodes.stump006.geometry} material={materials.grass} position={[1.16, 0.05, 0.83]} />
      <mesh geometry={nodes.stump003.geometry} material={materials.grass} position={[1.64, 0.06, 1.44]} />
      <mesh geometry={nodes.stump007.geometry} material={materials.grass} position={[1.64, 0.06, 1.44]} />
      <mesh geometry={nodes.firewood.geometry} material={materials.grass} position={[1.86, 0, 0.94]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.firewood004.geometry} material={materials.grass} position={[1.86, 0, 0.94]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.firewood001.geometry} material={materials.grass} position={[1.6, 0, 1.76]} rotation={[-Math.PI, 0.26, -Math.PI]} />
      <mesh geometry={nodes.firewood005.geometry} material={materials.grass} position={[1.6, 0, 1.76]} rotation={[-Math.PI, 0.26, -Math.PI]} />
      <mesh geometry={nodes.firewood002.geometry} material={materials.grass} position={[1.34, 0, 0.34]} rotation={[0, 1.31, 0]} />
      <mesh geometry={nodes.firewood006.geometry} material={materials.grass} position={[1.34, 0, 0.34]} rotation={[0, 1.31, 0]} />
      <mesh geometry={nodes.firewood003.geometry} material={materials.grass} position={[1.69, 0.05, 0.87]} rotation={[Math.PI, -0.17, 2.58]} />
      <mesh geometry={nodes.firewood007.geometry} material={materials.grass} position={[1.69, 0.05, 0.87]} rotation={[Math.PI, -0.17, 2.58]} />
      <mesh geometry={nodes.axe_handle.geometry} material={materials.grass} position={[1.13, 0.18, 0.81]} rotation={[0, 0, Math.PI / 9]} />
      <mesh geometry={nodes.axe_handle001.geometry} material={materials.grass} position={[1.13, 0.18, 0.81]} rotation={[0, 0, Math.PI / 9]} />
      <mesh geometry={nodes.axe_head.geometry} material={materials.metal} position={[1.15, 0.13, 0.81]} rotation={[0, 0, Math.PI / 9]} />
      <mesh geometry={nodes.axe_head001.geometry} material={materials.metal} position={[1.15, 0.13, 0.81]} rotation={[0, 0, Math.PI / 9]} />
      <mesh geometry={nodes.pole001.geometry} material={materials.grass} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.pole002.geometry} material={materials.grass} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.housing001.geometry} material={materials.metal} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.housing002.geometry} material={materials.metal} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.mount001.geometry} material={materials.grass} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.mount002.geometry} material={materials.grass} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.pole.geometry} material={materials.grass} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.housing.geometry} material={materials.metal} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.mount.geometry} material={materials.grass} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.rock.geometry} material={materials.grass} position={[-1.28, 0, -1.34]} />
      <mesh geometry={nodes.rock023.geometry} material={materials.grass} position={[-1.28, 0, -1.34]} />
      <mesh geometry={nodes.rock011.geometry} material={materials.grass} position={[1.32, 0, -1.39]} />
      <mesh geometry={nodes.rock024.geometry} material={materials.grass} position={[1.32, 0, -1.39]} />
      <mesh geometry={nodes.rock001.geometry} material={materials.grass} position={[1.55, 0, -0.35]} />
      <mesh geometry={nodes.rock025.geometry} material={materials.grass} position={[1.55, 0, -0.35]} />
      <mesh geometry={nodes.rock020.geometry} material={materials.grass} position={[-1.29, 0, 0.14]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock026.geometry} material={materials.grass} position={[-1.29, 0, 0.14]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock002.geometry} material={materials.grass} position={[-1.3, 0, 0.75]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock027.geometry} material={materials.grass} position={[-1.3, 0, 0.75]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock012.geometry} material={materials.grass} position={[-1.78, 0, 0.5]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock028.geometry} material={materials.grass} position={[-1.78, 0, 0.5]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock003.geometry} material={materials.grass} position={[-1.39, 0, 1.49]} />
      <mesh geometry={nodes.rock029.geometry} material={materials.grass} position={[-1.39, 0, 1.49]} />
      <mesh geometry={nodes.rock019.geometry} material={materials.grass} position={[1.2, 0, -0.67]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock030.geometry} material={materials.grass} position={[1.2, 0, -0.67]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock004.geometry} material={materials.grass} position={[1.62, 0, -0.75]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.rock031.geometry} material={materials.grass} position={[1.62, 0, -0.75]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.rock013.geometry} material={materials.grass} position={[1.77, 0, 0]} rotation={[0, -0.26, 0]} />
      <mesh geometry={nodes.rock032.geometry} material={materials.grass} position={[1.77, 0, 0]} rotation={[0, -0.26, 0]} />
      <mesh geometry={nodes.rock005.geometry} material={materials.grass} position={[1.37, 0, -0.02]} />
      <mesh geometry={nodes.rock033.geometry} material={materials.grass} position={[1.37, 0, -0.02]} />
      <mesh geometry={nodes.rock018.geometry} material={materials.grass} position={[-1.56, 0, -0.57]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock034.geometry} material={materials.grass} position={[-1.56, 0, -0.57]} rotation={[0, Math.PI / 4, 0]} />
      <mesh geometry={nodes.rock006.geometry} material={materials.grass} position={[-1.65, 0, 0.17]} />
      <mesh geometry={nodes.rock035.geometry} material={materials.grass} position={[-1.65, 0, 0.17]} />
      <mesh geometry={nodes.rock007.geometry} material={materials.grass} position={[1.1, 0, -0.4]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.rock036.geometry} material={materials.grass} position={[1.1, 0, -0.4]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.rock017.geometry} material={materials.grass} position={[0.98, 0, 0.46]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.rock037.geometry} material={materials.grass} position={[0.98, 0, 0.46]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
      <mesh geometry={nodes.rock008.geometry} material={materials.grass} position={[0.89, 0, 1.2]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.rock038.geometry} material={materials.grass} position={[0.89, 0, 1.2]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.rock014.geometry} material={materials.grass} position={[-1.12, 0, -0.79]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock039.geometry} material={materials.grass} position={[-1.12, 0, -0.79]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock015.geometry} material={materials.grass} position={[-1.8, 0, 1.05]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock040.geometry} material={materials.grass} position={[-1.8, 0, 1.05]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock009.geometry} material={materials.grass} position={[-1.77, 0, -0.87]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock041.geometry} material={materials.grass} position={[-1.77, 0, -0.87]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock016.geometry} material={materials.grass} position={[-1.76, 0, -0.21]} rotation={[-Math.PI, 1.54, -Math.PI]} />
      <mesh geometry={nodes.rock010.geometry} material={materials.grass} position={[-1.12, 0, -0.79]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock021.geometry} material={materials.grass} position={[-1.22, 0, -0.43]} rotation={[0, 0.45, 0]} />
      <mesh geometry={nodes.rock022.geometry} material={materials.grass} position={[-1.46, 0, -0.25]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.rock045.geometry} material={materials.grass} position={[-1.46, 0, -0.25]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes.portal.geometry} material={materials.grass} position={[-0.42, 0.76, -1.15]} rotation={[0, 0, -2.06]} />
      <mesh geometry={nodes.portal002.geometry} material={materials.grass} position={[-0.42, 0.76, -1.15]} rotation={[0, 0, -2.06]} />
      <mesh geometry={nodes.stairs001.geometry} material={materials.grass} position={[0, 0.06, -1.36]} />
      <mesh geometry={nodes.stairs003.geometry} material={materials.grass} position={[0, 0.06, -1.36]} />
      <mesh geometry={nodes.stairs.geometry} material={materials.grass} position={[0, 0.06, -1.05]} />
      <mesh geometry={nodes.stairs004.geometry} material={materials.grass} position={[0, 0.06, -1.05]} />
      <mesh geometry={nodes.stairs002.geometry} material={materials.grass} position={[0, 0, -1.77]} />
      <mesh geometry={nodes.stairs005.geometry} material={materials.grass} position={[0, 0, -1.77]} />
      <mesh geometry={nodes.lamp.geometry} material={materials.lampLight} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.lamp001.geometry} material={materials.lampLight} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.lamp002.geometry} material={materials.lampLight} position={[1.01, 0, -0.09]} />
      <mesh geometry={nodes.lamp003.geometry} material={materials.lampLight} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.portal001.geometry} material={materials.portalLight} position={[0, 0.55, -1.81]} rotation={[Math.PI / 2, 0, 0]} scale={[0.65, 0.59, 0.52]} />
      <mesh geometry={nodes.portal003.geometry} material={materials.portalLight} position={[0, 0.55, -1.81]} rotation={[Math.PI / 2, 0, 0]} scale={[0.65, 0.59, 0.52]} />
      <mesh geometry={nodes.fence008.geometry} material={materials.grass} position={[0.73, 0.22, 0.49]} rotation={[Math.PI / 2, 0, -3.05]} />
      <mesh geometry={nodes.fence009.geometry} material={materials.grass} position={[0.78, 0.22, -0.51]} rotation={[Math.PI / 2, 0, 3.13]} />
      <mesh geometry={nodes.fence010.geometry} material={materials.grass} position={[-0.92, 0.22, 1.47]} rotation={[Math.PI / 2, 0, 0.09]} />
      <mesh geometry={nodes.fence011.geometry} material={materials.grass} position={[-0.83, 0.22, 0.49]} rotation={[Math.PI / 2, 0, 0.02]} />
      <mesh geometry={nodes.fence012.geometry} material={materials.grass} position={[-0.79, 0.22, -0.5]} rotation={[Math.PI / 2, 0, 0.15]} />
      <mesh geometry={nodes.pole003.geometry} material={materials.grass} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.housing003.geometry} material={materials.metal} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.mount003.geometry} material={materials.grass} position={[-1.1, 0, -0.09]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.rock042.geometry} material={materials.grass} position={[-1.76, 0, -0.21]} rotation={[-Math.PI, 1.54, -Math.PI]} />
      <mesh geometry={nodes.rock043.geometry} material={materials.grass} position={[-1.12, 0, -0.79]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} />
      <mesh geometry={nodes.rock044.geometry} material={materials.grass} position={[-1.22, 0, -0.43]} rotation={[0, 0.45, 0]} />
    </group>
  )
}

useGLTF.preload('/portal-transformed.glb')
