/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/telescope.glb --transform -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['4012']: THREE.Mesh
    ['10003']: THREE.Mesh
    ['11002']: THREE.Mesh
    ['12003']: THREE.Mesh
    ['13003']: THREE.Mesh
    ['14003']: THREE.Mesh
    ['15003']: THREE.Mesh
    ['16003']: THREE.Mesh
    ['17003']: THREE.Mesh
    ['18003']: THREE.Mesh
    ['19003']: THREE.Mesh
    ['2006']: THREE.Mesh
    ['1006']: THREE.Mesh
    ['4015']: THREE.Mesh
    ['6025']: THREE.Mesh
    ['6026']: THREE.Mesh
    ['8022']: THREE.Mesh
    ['8023']: THREE.Mesh
    Cube019: THREE.Mesh
    Cube019_1: THREE.Mesh
    ['4020']: THREE.Mesh
    ['6035']: THREE.Mesh
    ['6036']: THREE.Mesh
    ['8030']: THREE.Mesh
    ['8031']: THREE.Mesh
    ['4018']: THREE.Mesh
    ['6031']: THREE.Mesh
    ['6032']: THREE.Mesh
    ['8027']: THREE.Mesh
    ['8028']: THREE.Mesh
    Cube020: THREE.Mesh
    Cube020_1: THREE.Mesh
    ['4017']: THREE.Mesh
    ['6029']: THREE.Mesh
    ['6030']: THREE.Mesh
    ['8025']: THREE.Mesh
    ['8026']: THREE.Mesh
    ['4021']: THREE.Mesh
    ['6037']: THREE.Mesh
    ['6038']: THREE.Mesh
    ['8032']: THREE.Mesh
    ['8033']: THREE.Mesh
    Cube021: THREE.Mesh
    Cube021_1: THREE.Mesh
    ['4014']: THREE.Mesh
    ['6023']: THREE.Mesh
    ['6024']: THREE.Mesh
    ['8020']: THREE.Mesh
    ['8021']: THREE.Mesh
    ['3009']: THREE.Mesh
    ['20003']: THREE.Mesh
    ['21003']: THREE.Mesh
    ['22003']: THREE.Mesh
    ['23003']: THREE.Mesh
    ['6021']: THREE.Mesh
    ['5009']: THREE.Mesh
    ['4013']: THREE.Mesh
    ['3014']: THREE.Mesh
    ['2007']: THREE.Mesh
    ['1007']: THREE.Mesh
    ['3015']: THREE.Mesh
    ['5012']: THREE.Mesh
    ['5013']: THREE.Mesh
    ['6022']: THREE.Mesh
    ['6033']: THREE.Mesh
    ['7007']: THREE.Mesh
    ['8024']: THREE.Mesh
    ['4016']: THREE.Mesh
    ['3010']: THREE.Mesh
    ['2009']: THREE.Mesh
    ['1008']: THREE.Mesh
    ['3011']: THREE.Mesh
    ['5014']: THREE.Mesh
    ['5015']: THREE.Mesh
    ['6028']: THREE.Mesh
    ['6039']: THREE.Mesh
    ['7008']: THREE.Mesh
    ['8029']: THREE.Mesh
    ['4019']: THREE.Mesh
    ['3012']: THREE.Mesh
    ['2008']: THREE.Mesh
    ['1009']: THREE.Mesh
    ['3013']: THREE.Mesh
    ['5010']: THREE.Mesh
    ['5011']: THREE.Mesh
    ['6027']: THREE.Mesh
    ['6034']: THREE.Mesh
    ['7006']: THREE.Mesh
    ['8019']: THREE.Mesh
    ['7005']: THREE.Mesh
    ['8018']: THREE.Mesh
    ['9003']: THREE.Mesh
    ['32002']: THREE.Mesh
    ['10004']: THREE.Mesh
    ['1010']: THREE.Mesh
    ['2010']: THREE.Mesh
    ['3016']: THREE.Mesh
    ['4022']: THREE.Mesh
    ['5016']: THREE.Mesh
    ['6040']: THREE.Mesh
    ['8034']: THREE.Mesh
    ['9004']: THREE.Mesh
    glass002: THREE.Mesh
    ['18004']: THREE.Mesh
    ['11007']: THREE.Mesh
    ['11008']: THREE.Mesh
    ['11009']: THREE.Mesh
    ['11010']: THREE.Mesh
    ['12004']: THREE.Mesh
    ['13004']: THREE.Mesh
    ['14004']: THREE.Mesh
    ['15004']: THREE.Mesh
    ['16004']: THREE.Mesh
    ['17004']: THREE.Mesh
    ['19004']: THREE.Mesh
    ['20004']: THREE.Mesh
    ['21004']: THREE.Mesh
    ['22004']: THREE.Mesh
    ['23004']: THREE.Mesh
    ['24002']: THREE.Mesh
    ['25003']: THREE.Mesh
    ['25004']: THREE.Mesh
    ['26003']: THREE.Mesh
    Cube025: THREE.Mesh
    Cube025_1: THREE.Mesh
    ['27003']: THREE.Mesh
    ['27004']: THREE.Mesh
    ['28002']: THREE.Mesh
    ['29002']: THREE.Mesh
    ['30002']: THREE.Mesh
    ['31002']: THREE.Mesh
    ['33002']: THREE.Mesh
    ['34002']: THREE.Mesh
    ['35002']: THREE.Mesh
    ['36002']: THREE.Mesh
    ['37002']: THREE.Mesh
    ['38002']: THREE.Mesh
    ['40002']: THREE.Mesh
    ['41002']: THREE.Mesh
    ['42002']: THREE.Mesh
    ['43002']: THREE.Mesh
    ['44002']: THREE.Mesh
    ['45002']: THREE.Mesh
    glass003: THREE.Mesh
  }
  materials: {
    Hardware: THREE.MeshBasicMaterial
    ['black outliner 0.05']: THREE.MeshStandardMaterial
    optics_white_hdr: THREE.MeshBasicMaterial
    lens: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/telescope-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4012'].geometry} material={materials.Hardware} position={[0.08, 0.39, -0.1]}>
        <mesh geometry={nodes['10003'].geometry} material={materials['black outliner 0.05']} />
        <mesh geometry={nodes['11002'].geometry} material={materials['black outliner 0.05']} />
        <mesh geometry={nodes['12003'].geometry} material={materials['black outliner 0.05']} />
        <mesh geometry={nodes['13003'].geometry} material={materials.Hardware} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes['14003'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['15003'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 1.13, 0]} />
        <mesh geometry={nodes['16003'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['17003'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['18003'].geometry} material={materials.Hardware} rotation={[0, 0, Math.PI]} />
        <mesh geometry={nodes['19003'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 1.13, 0]} />
        <mesh geometry={nodes['2006'].geometry} material={materials['black outliner 0.05']} rotation={[0, 0.01, 0]}>
          <mesh geometry={nodes['1006'].geometry} material={materials.Hardware} rotation={[-Math.PI, Math.PI / 3, -Math.PI]}>
            <mesh geometry={nodes['4015'].geometry} material={materials.Hardware} rotation={[-1.47, 0.17, 2.61]}>
              <mesh geometry={nodes['6025'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6026'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8022'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8023'].geometry} material={materials.Hardware} />
              <group rotation={[Math.PI, 1.28, -Math.PI / 2]}>
                <mesh geometry={nodes.Cube019.geometry} material={materials.Hardware} />
                <mesh geometry={nodes.Cube019_1.geometry} material={materials.Hardware} />
                <mesh geometry={nodes['4020'].geometry} material={materials.Hardware} rotation={[-0.44, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes['6035'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['6036'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['8030'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['8031'].geometry} material={materials.Hardware} />
                </mesh>
              </group>
            </mesh>
            <mesh geometry={nodes['4018'].geometry} material={materials.Hardware} rotation={[-1.76, 0, -Math.PI / 2]}>
              <mesh geometry={nodes['6031'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6032'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8027'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8028'].geometry} material={materials.Hardware} />
              <group rotation={[Math.PI, 1.28, -1.57]}>
                <mesh geometry={nodes.Cube020.geometry} material={materials.Hardware} />
                <mesh geometry={nodes.Cube020_1.geometry} material={materials.Hardware} />
                <mesh geometry={nodes['4017'].geometry} material={materials.Hardware} rotation={[-0.44, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes['6029'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['6030'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['8025'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['8026'].geometry} material={materials.Hardware} />
                </mesh>
              </group>
            </mesh>
            <mesh geometry={nodes['4021'].geometry} material={materials.Hardware} rotation={[-1.48, -0.15, 0.53]}>
              <mesh geometry={nodes['6037'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6038'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8032'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8033'].geometry} material={materials.Hardware} />
              <group rotation={[Math.PI, 1.28, -Math.PI / 2]}>
                <mesh geometry={nodes.Cube021.geometry} material={materials.Hardware} />
                <mesh geometry={nodes.Cube021_1.geometry} material={materials.Hardware} />
                <mesh geometry={nodes['4014'].geometry} material={materials.Hardware} rotation={[-0.44, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes['6023'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['6024'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['8020'].geometry} material={materials.Hardware} />
                  <mesh geometry={nodes['8021'].geometry} material={materials.Hardware} />
                </mesh>
              </group>
            </mesh>
          </mesh>
          <mesh geometry={nodes['3009'].geometry} material={materials['black outliner 0.05']} />
        </mesh>
        <mesh geometry={nodes['20003'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 1.13, 0]} />
        <mesh geometry={nodes['21003'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 1.13, 0]} />
        <mesh geometry={nodes['22003'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 1.13, 0]} />
        <mesh geometry={nodes['23003'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 1.13, 0]} />
        <mesh geometry={nodes['6021'].geometry} material={materials['black outliner 0.05']}>
          <mesh geometry={nodes['5009'].geometry} material={materials.Hardware} rotation={[-Math.PI, Math.PI / 3, -Math.PI]}>
            <mesh geometry={nodes['4013'].geometry} material={materials.Hardware} rotation={[-2.39, -0.9, 2.2]}>
              <mesh geometry={nodes['3014'].geometry} material={materials['black outliner 0.05']} rotation={[0, 0, Math.PI / 2]}>
                <mesh geometry={nodes['2007'].geometry} material={materials['black outliner 0.05']}>
                  <mesh geometry={nodes['1007'].geometry} material={materials['black outliner 0.05']} />
                </mesh>
                <mesh geometry={nodes['3015'].geometry} material={materials.Hardware} />
              </mesh>
              <mesh geometry={nodes['5012'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['5013'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6022'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6033'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['7007'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8024'].geometry} material={materials.Hardware} />
            </mesh>
            <mesh geometry={nodes['4016'].geometry} material={materials.Hardware} rotation={[-0.44, 0, -Math.PI / 2]}>
              <mesh geometry={nodes['3010'].geometry} material={materials['black outliner 0.05']} rotation={[0, 0, Math.PI / 2]}>
                <mesh geometry={nodes['2009'].geometry} material={materials['black outliner 0.05']}>
                  <mesh geometry={nodes['1008'].geometry} material={materials['black outliner 0.05']} />
                </mesh>
                <mesh geometry={nodes['3011'].geometry} material={materials.Hardware} />
              </mesh>
              <mesh geometry={nodes['5014'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['5015'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6028'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6039'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['7008'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8029'].geometry} material={materials.Hardware} />
            </mesh>
            <mesh geometry={nodes['4019'].geometry} material={materials.Hardware} rotation={[-2.39, 0.9, 0.94]}>
              <mesh geometry={nodes['3012'].geometry} material={materials['black outliner 0.05']} rotation={[0, 0, Math.PI / 2]}>
                <mesh geometry={nodes['2008'].geometry} material={materials['black outliner 0.05']}>
                  <mesh geometry={nodes['1009'].geometry} material={materials['black outliner 0.05']} />
                </mesh>
                <mesh geometry={nodes['3013'].geometry} material={materials.Hardware} />
              </mesh>
              <mesh geometry={nodes['5010'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['5011'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6027'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['6034'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['7006'].geometry} material={materials.Hardware} />
              <mesh geometry={nodes['8019'].geometry} material={materials.Hardware} />
            </mesh>
          </mesh>
          <mesh geometry={nodes['7005'].geometry} material={materials['black outliner 0.05']} />
        </mesh>
        <mesh geometry={nodes['8018'].geometry} material={materials['black outliner 0.05']} />
        <mesh geometry={nodes['9003'].geometry} material={materials.Hardware} />
      </mesh>
      <mesh geometry={nodes['32002'].geometry} material={materials.optics_white_hdr} position={[0.08, 0.39, -0.1]} rotation={[1.03, 0.23, -1.44]}>
        <mesh geometry={nodes['10004'].geometry} material={materials.optics_white_hdr} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes['1010'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['2010'].geometry} material={materials.Hardware} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['3016'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['4022'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['5016'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['6040'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['8034'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['9004'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes.glass002.geometry} material={materials.lens} rotation={[0, 0, Math.PI]} />
        </mesh>
        <mesh geometry={nodes['18004'].geometry} material={materials.optics_white_hdr} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes['11007'].geometry} material={materials.optics_white_hdr} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes['11008'].geometry} material={materials.optics_white_hdr} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes['11009'].geometry} material={materials.optics_white_hdr} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes['11010'].geometry} material={materials.optics_white_hdr} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes['12004'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['13004'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['14004'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['15004'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['16004'].geometry} material={materials.Hardware} />
          <mesh geometry={nodes['17004'].geometry} material={materials.Hardware} />
        </mesh>
        <mesh geometry={nodes['19004'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['20004'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['21004'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['22004'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['23004'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['24002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['25003'].geometry} material={materials.optics_white_hdr} rotation={[0, Math.PI / 3, -1.57]} />
        <mesh geometry={nodes['25004'].geometry} material={materials.optics_white_hdr} rotation={[0, Math.PI / 3, -1.57]} />
        <mesh geometry={nodes['26003'].geometry} material={materials.optics_white_hdr} rotation={[-Math.PI, Math.PI / 3, 1.57]} />
        <group rotation={[-Math.PI, Math.PI / 3, 1.57]}>
          <mesh geometry={nodes.Cube025.geometry} material={materials.Hardware} />
          <mesh geometry={nodes.Cube025_1.geometry} material={materials.Hardware} />
        </group>
        <mesh geometry={nodes['27003'].geometry} material={materials.optics_white_hdr} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['27004'].geometry} material={materials.optics_white_hdr} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['28002'].geometry} material={materials.Hardware} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['29002'].geometry} material={materials.Hardware} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['30002'].geometry} material={materials.Hardware} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['31002'].geometry} material={materials.Hardware} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['33002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['34002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['35002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['36002'].geometry} material={materials.optics_white_hdr} />
        <mesh geometry={nodes['37002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['38002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['40002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['41002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['42002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['43002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['44002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes['45002'].geometry} material={materials.Hardware} />
        <mesh geometry={nodes.glass003.geometry} material={materials.lens} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/telescope-transformed.glb')
